In [6]:
from pprint import pprint
import numpy as np

def method_Jacobi(A, b, Iterations):
                                                                                                                                                       
    x = np.zeros(len(A[0]))
                                                                                                                                                                   
    D = np.diag(A)
    L_plus_R = A - np.diagflat(D)
                                                                                                                                                                           
    for i in range(Iterations):
        old_x = x
        xn = (b - np.dot(L_plus_R,x)) / D
        x = xn
    
    # Точность определяем в упрощённой форме: ||x_(k+1) - x_(k)|| 
    # и считаем количество нулей до первой ненулевой цифры
    epsilon = str(max(np.abs(xn - old_x)))
    j = 0
    while epsilon[j] == '0':
        if j == 0:
            j = j + 2
        else:
            j = j + 1
    if j >= 2:
        j = j - 1
        
    return [x, j]

In [3]:
A = np.array([[10,1,-2],[1,-5,1],[3,-1,2]])
b = np.array([10,10,-5])

In [7]:
sol = method_Jacobi(A,b,Iterations=5)

print("A:")
pprint(A)

print("b:")
pprint(b)

print("x:")
pprint(sol[0])

print(f"Гарантировано верных знаков: {sol[1]}")

A:
array([[10,  1, -2],
       [ 1, -5,  1],
       [ 3, -1,  2]])
b:
array([10, 10, -5])
x:
array([ 0.4344, -2.7858, -4.466 ])
Гарантировано верных знаков: 1
